version: '3.8'

services:
  app:
    build: .
    image: spring-boot-learning-guide
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"