apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-learning-guide.fullname" . }}
  labels:
    app: {{ include "spring-boot-learning-guide.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spring-boot-learning-guide.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "spring-boot-learning-guide.name" . }}
    spec:
      containers:
        - name: {{ include "spring-boot-learning-guide.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}